#' @name catch.conditions
#' @title Condition Handling and Recovery
#' @description This function provides a mechanism for handling unusual
#' conditions such as errors and warnings.
#'
#' @param expr expression to be evaluated.
#'
#' @details The function calls \link{withCallingHandlers} and \link{tryCatch} to
#' catch and return, after the evaluation of \code{expr}, any unusual conditions
#'  such as errors and warnings.
#'
#' Conditions are represented as objects that contain information about the
#' condition that occurred, such as a message and the call in which the
#' condition occurred.
#'
#' @return A named list of two elements:
#' \item{value}{the result of the evaluation, a regular R object or an error
#' message.}
#' \item{warning}{any warning message generated by the evaluation, \code{NULL}
#' if none.}
#'
#' @export catch.conditions
#'
#' @seealso \link{tryCatch}.
#'
#' @author The R core Team.
#
catch.conditions <- function (expr) {
  W <- NULL
  w.handler <- function(w) {
    W <<- w
    invokeRestart("muffleWarning")
  }
  list(value = withCallingHandlers(tryCatch(expr, error = function(e) e),
                                   warning = w.handler), warning = W)
}
