#' @title 200 trios formed from the GTEx tissue WholeBlood
#' @references The GTEx Consortium. GTEx Analysis V8 (dbGaP Accession phs000424.v8.p2). https:// gtexportal.org/home/datasets, 2021. [Online; accessed 8-June-2020]
#' @description A list of dataframes where each dataframe represents a single trio from one of the 5 model topologies
#' @docType data
#' @format a list of length = 200 where each element is an 670 X 3 dataframe where the first
#'  column is an eQTL representing V1 and columns 2:3 are the cis and trans targets representing
#'  T1 and T2 (respectively)
"WBtrios"

#' @title A simulated M1 trio with 1000 observations
#'
#' @description A 1000 X 3 dataframe where V1 is a simulated eQTL and T1 and T2 are simulated molecular phenotypes
#' @docType data
#' @format dataframe 1000 X 3
"M1trio"

#' @title The rotated variables from the whole-genome level expression PCA for the GTEx tissue Whole Blood
#'
#' @description A 670 X 670 dataframe of PCA scores where the rows are observations and the columns are the PCs
#' @docType data
#' @format dataframe 670 X 670
"WBscores"


#' @title 100 CNA trios where the first column of each trio corresponds to the Copy Number Alteration,
#' the second and third columns are the expression and methylation targets of the genetic variant. The remaining
#' columns correspond to each trios identified confounding variables
#'
#' @description A 670 X 670 dataframe of PCA scores where the rows are observations and the columns are the PCs
#' @references The example data here are taken in whole or part from data generated by the TCGA Research Network: https://www.cancer.gov/tcga."
#' @description A list of dataframes where each dataframe represents a single CNA trio with confounders
#' @docType data
#' @format a list of length = 100 where each element is an 564 X 3+n dataframe where the first
#'  column is the CNA representing V1 and columns 2:3 are the expression and Methylation targets representing
#'  T1 and T2 (respectively) and the remaining columns are selected confounding covariates
"CNAtrios"
